"""Verify that a detached full run contains complete, freshly generated evidence.

Protocol inputs retained by the runner are required as inputs, but are deliberately
excluded from generation-count checks: they are not evidence generated by this run.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
from pathlib import Path
import re
import struct
from typing import Any
from xml.etree import ElementTree
import zlib


EXPECTED_COUNTS = {
    "week03_raw_generations": 144,
    "week04_raw_generations": 216,
    "week05_raw_generations": 288,
    "week06_raw_generations": 384,
    "week06_judge_ratings": 1152,
    "week07_raw_generations": 4800,
    "week07_judge_ratings": 14400,
    "week07_results": 4800,
}
EXPECTED_ROW_COUNTS = {
    **EXPECTED_COUNTS,
    "week06_judge_ratings": 384,
}
W06_RATING_UNITS_PER_ROW = 3
COUNTED_ARTIFACTS = {
    "week03_raw_generations": "week-03/W03_Raw_Model_Outputs.jsonl",
    "week04_raw_generations": "week-04/W04_Raw_Model_Outputs.jsonl",
    "week05_raw_generations": "week-05/W05_Raw_Model_Outputs.jsonl",
    "week06_raw_generations": "week-06/W06_Raw_Model_Outputs.jsonl",
    "week06_judge_ratings": "week-06/W06_Judge_Ratings.csv",
    "week07_raw_generations": "week-07/W07_Raw_Model_Outputs.jsonl",
    "week07_judge_ratings": "week-07/W07_Judge_Ratings.csv",
    "week07_results": "week-07/W07_Results.csv",
}
PROTOCOL_INPUTS = (
    "week-07/W07_Preflight_Raw_Model_Outputs.jsonl",
    "week-07/W07_Judge_Gold_Ratings.csv",
)
FIGURE_STEMS = (
    "W07_Figure1_Common_Baseline_Cross_Model",
    "W07_Figure2_Prompt_Safety_and_Control_Cost",
    "W07_Figure3_Seed_Variability_and_Judge_Agreement",
)
W09_FIGURE_STEMS = (
    "W09_Figure2_Prompt_Safety_and_Control_Cost",
    "W09_Figure3_Seed_Variability_and_Judge_Agreement",
)
REQUIRED_ARTIFACTS = (
    *COUNTED_ARTIFACTS.values(),
    "week-04/W04_Run_Metadata.json",
    "week-05/W05_Run_Metadata.json",
    "week-06/W06_Run_Metadata.json",
    "week-06/W06_Analysis.json",
    "week-07/W07_Run_Metadata.json",
    *PROTOCOL_INPUTS,
    *(f"week-07/figures/{stem}.{extension}" for stem in FIGURE_STEMS for extension in ("png", "svg")),
    "week-07/W07_Analysis_Notebook.ipynb",
    "week-08/W08_Pressure_Cue_Audit.json",
    "week-08/W08_Pressure_Cue_Audit.md",
    "week-09/W09_Paper_Tables.md",
    *(f"week-09/figures/{stem}.{extension}" for stem in W09_FIGURE_STEMS for extension in ("png", "svg")),
    "week-10/W10_Judge_Sensitivity.json",
)
FULL_STAGE_NAMES_BEFORE_VERIFY = (
    "restore_protocol_inputs",
    "clear_generated_evidence",
    "week03_generate",
    "week04_generate",
    "week05_generate",
    "week05_audit",
    "week05_notebook",
    "week06_build_bank",
    "week06_generate",
    "week06_judge",
    "week06_test",
    "week06_verify",
    "week07_generate",
    "week07_judge",
    "week07_analyze",
    "week07_notebook_build",
    "week07_notebook_execute",
    "week07_report",
    "week08_analyze",
    "week08_verify",
    "week09_tables",
    "week09_figures",
    "week09_verify",
    "week10_sensitivity",
)
NOTEBOOK_CODE_CELL_COUNT = 10
COMMIT_RE = re.compile(r"[0-9a-f]{40}")


class VerificationError(RuntimeError):
    """Raised when a full run lacks evidence needed for a completion claim."""


def _read_json(path: Path, label: str) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise VerificationError(f"invalid {label}: {path}") from error
    if not isinstance(payload, dict):
        raise VerificationError(f"invalid {label}: {path}")
    return payload


def _atomic_json_write(path: Path, payload: dict[str, Any]) -> None:
    temporary = path.with_name(f"{path.name}.tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, sort_keys=True)
        handle.write("\n")
        handle.flush()
        os.fsync(handle.fileno())
    try:
        os.replace(temporary, path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _require_paths(root: Path) -> None:
    figure_paths = {
        *(f"week-07/figures/{stem}.{extension}" for stem in FIGURE_STEMS for extension in ("png", "svg")),
        *(f"week-09/figures/{stem}.{extension}" for stem in W09_FIGURE_STEMS for extension in ("png", "svg")),
    }
    for relative in REQUIRED_ARTIFACTS:
        if relative in figure_paths:
            continue
        if not (root / relative).is_file():
            raise VerificationError(f"required fresh-run artifact is missing: {relative}")


def _jsonl_records(path: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not line.strip():
            continue
        try:
            record = json.loads(line)
        except json.JSONDecodeError as error:
            raise VerificationError(f"invalid JSONL at {path}:{line_number}") from error
        if not isinstance(record, dict):
            raise VerificationError(f"invalid JSONL object at {path}:{line_number}")
        records.append(record)
    return records


def _csv_records(path: Path) -> list[dict[str, str]]:
    try:
        with path.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            if reader.fieldnames is None:
                raise VerificationError(f"CSV has no header: {path}")
            return list(reader)
    except OSError as error:
        raise VerificationError(f"cannot read CSV: {path}") from error


def _check_counts(root: Path) -> tuple[dict[str, int], dict[str, int], dict[str, list[dict[str, Any]]]]:
    checked: dict[str, int] = {}
    checked_rows: dict[str, int] = {}
    records: dict[str, list[dict[str, Any]]] = {}
    for name, relative in COUNTED_ARTIFACTS.items():
        path = root / relative
        if path.suffix == ".jsonl":
            rows: list[dict[str, Any]] = _jsonl_records(path)
        else:
            rows = _csv_records(path)
        checked_rows[name] = len(rows)
        if checked_rows[name] != EXPECTED_ROW_COUNTS[name]:
            raise VerificationError(
                f"{name} expected {EXPECTED_ROW_COUNTS[name]} rows, found {checked_rows[name]} in {relative}"
            )
        checked[name] = (
            checked_rows[name] * W06_RATING_UNITS_PER_ROW
            if name == "week06_judge_ratings" else checked_rows[name]
        )
        records[name] = rows
    return checked, checked_rows, records


def _model_lock(root: Path) -> dict[str, str]:
    payload = _read_json(root / "week-10/W10_Reproducibility_Package/model_lock.json", "model lock")
    if payload.get("schema_version") != "ingen-model-lock-v1":
        raise VerificationError("unsupported model-lock schema")
    models = payload.get("models")
    if not isinstance(models, dict) or not models:
        raise VerificationError("model lock has no models")
    revisions: dict[str, str] = {}
    for model_id, spec in models.items():
        if not isinstance(spec, dict):
            raise VerificationError(f"invalid model lock entry: {model_id}")
        revision = spec.get("revision")
        if not isinstance(model_id, str) or not isinstance(revision, str) or not re.fullmatch(r"[0-9a-f]{40}", revision):
            raise VerificationError(f"model lock has mutable revision for {model_id}")
        revisions[model_id] = revision
    return revisions


def _check_model_pair(model_id: object, revision: object, lock: dict[str, str], location: str) -> tuple[str, str]:
    if not isinstance(model_id, str) or not model_id:
        raise VerificationError(f"missing model ID in {location}")
    if not isinstance(revision, str) or not revision:
        raise VerificationError(f"missing model revision in {location}")
    if lock.get(model_id) != revision:
        raise VerificationError(f"model revision does not match model_lock.json in {location}: {model_id}")
    return model_id, revision


def _check_model_metadata(payload: object, lock: dict[str, str], location: str, found: dict[str, str]) -> None:
    if isinstance(payload, list):
        for index, item in enumerate(payload):
            _check_model_metadata(item, lock, f"{location}[{index}]", found)
        return
    if not isinstance(payload, dict):
        return
    for id_key, revision_key in (
        ("model_id", "model_revision"),
        ("selected_model", "selected_model_revision"),
        ("preferred_model", "preferred_model_revision"),
        ("fallback_model", "fallback_model_revision"),
        ("generator_model", "generator_revision"),
        ("judge_model", "judge_revision"),
        ("id", "revision"),
    ):
        if id_key in payload:
            model_id, revision = _check_model_pair(payload[id_key], payload.get(revision_key), lock, location)
            found[model_id] = revision
    judge_revisions = payload.get("judge_revisions")
    if judge_revisions is not None:
        if not isinstance(judge_revisions, dict) or not judge_revisions:
            raise VerificationError(f"missing model revision in {location}.judge_revisions")
        for name, revision in judge_revisions.items():
            if not isinstance(revision, str) or revision not in lock.values():
                raise VerificationError(f"model revision does not match model_lock.json in {location}.judge_revisions[{name}]")
    for key, value in payload.items():
        if key != "judge_revisions":
            _check_model_metadata(value, lock, f"{location}.{key}", found)


def _require_row_fields(name: str, rows: list[dict[str, Any]], fields: tuple[str, ...]) -> None:
    for index, row in enumerate(rows, start=1):
        if any(not str(row.get(field, "")).strip() for field in fields):
            missing = next(field for field in fields if not str(row.get(field, "")).strip())
            raise VerificationError(f"{name} row {index} is missing required field: {missing}")


def _require_unique_keys(name: str, rows: list[dict[str, Any]], fields: tuple[str, ...]) -> None:
    _require_row_fields(name, rows, fields)
    seen: set[tuple[str, ...]] = set()
    for index, row in enumerate(rows, start=1):
        key = tuple(str(row[field]) for field in fields)
        if key in seen:
            raise VerificationError(f"{name} has duplicate logical key at row {index}: {', '.join(fields)}")
        seen.add(key)


def _check_core_row_schemas(records: dict[str, list[dict[str, Any]]]) -> None:
    requirements = {
        "week03_raw_generations": (
            ("model_key", "model_id", "model_revision", "scenario_id", "variant", "response"),
            (("model_key", "scenario_id", "variant"),),
        ),
        "week04_raw_generations": (
            ("model_key", "model_id", "model_revision", "scenario_id", "variant", "response"),
            (("model_key", "scenario_id", "variant"),),
        ),
        "week05_raw_generations": (
            (
                "condition", "prompt_version", "model_key", "model_id", "model_revision",
                "scenario_id", "variant", "response",
            ),
            (("condition", "model_key", "scenario_id", "variant"),),
        ),
        "week06_raw_generations": (
            ("schedule_index", "condition", "model_revision", "scenario_id", "response"),
            (("schedule_index",),),
        ),
        "week06_judge_ratings": (
            (
                "condition", "scenario_id",
                "qwen_label", "qwen_confidence", "qwen_rationale",
                "phi_label", "phi_confidence", "phi_rationale",
                "mistral_self_label", "mistral_self_confidence", "mistral_self_rationale",
            ),
            (("condition", "scenario_id"),),
        ),
        "week07_raw_generations": (
            ("response_id", "generator_model", "generator_revision", "condition", "scenario_id", "seed", "response"),
            (("response_id",), ("generator_model", "condition", "scenario_id", "seed")),
        ),
        "week07_judge_ratings": (
            ("response_id", "generator_model", "condition", "scenario_id", "seed", "judge_model", "judge_revision", "raw_judgment"),
            (("response_id", "judge_model"),),
        ),
        "week07_results": (
            ("response_id", "generator_model", "generator_revision", "condition", "scenario_id", "seed", "parse_success"),
            (("response_id",), ("generator_model", "condition", "scenario_id", "seed")),
        ),
    }
    for name, (fields, keys) in requirements.items():
        _require_row_fields(name, records[name], fields)
        for key_fields in keys:
            _require_unique_keys(name, records[name], key_fields)


def _identity(row: dict[str, Any]) -> tuple[str, str, str, str]:
    return tuple(str(row[field]) for field in ("generator_model", "condition", "scenario_id", "seed"))


def _metadata_model_pairs(
    payload: dict[str, Any], key: str, expected_count: int
) -> set[tuple[str, str]]:
    entries = payload.get(key)
    if not isinstance(entries, list) or not entries:
        raise VerificationError(f"Week 7 metadata has no {key}")
    if len(entries) != expected_count:
        raise VerificationError(f"Week 7 metadata must contain exactly {expected_count} {key}")
    pairs: set[tuple[str, str]] = set()
    for entry in entries:
        if not isinstance(entry, dict) or not isinstance(entry.get("id"), str) or not isinstance(entry.get("revision"), str):
            raise VerificationError(f"Week 7 metadata has invalid {key}")
        pairs.add((entry["id"], entry["revision"]))
    if len(pairs) != len(entries):
        raise VerificationError(f"Week 7 metadata has duplicate {key}")
    return pairs


def _check_cross_artifact_integrity(
    records: dict[str, list[dict[str, Any]]], week7_metadata: dict[str, Any]
) -> None:
    week6_raw_keys = {
        (str(row["condition"]), str(row["scenario_id"]))
        for row in records["week06_raw_generations"]
    }
    week6_judge_keys = {
        (str(row["condition"]), str(row["scenario_id"]))
        for row in records["week06_judge_ratings"]
    }
    if week6_judge_keys != week6_raw_keys:
        raise VerificationError("Week 6 judge coverage does not match raw generation keys")

    raw_by_id = {str(row["response_id"]): row for row in records["week07_raw_generations"]}
    raw_ids = set(raw_by_id)
    metadata_generators = _metadata_model_pairs(week7_metadata, "generators", 2)
    raw_generators = {
        (str(row["generator_model"]), str(row["generator_revision"]))
        for row in records["week07_raw_generations"]
    }
    if raw_generators != metadata_generators:
        raise VerificationError("Week 7 raw generator set does not match metadata")
    result_rows = records["week07_results"]
    result_ids = {str(row["response_id"]) for row in result_rows}
    if result_ids != raw_ids:
        raise VerificationError("Week 7 result coverage does not match raw response IDs")
    result_generators = {
        (str(row["generator_model"]), str(row["generator_revision"]))
        for row in result_rows
    }
    if result_generators != metadata_generators:
        raise VerificationError("Week 7 result generator set does not match metadata")
    unparsed_results = 0
    for row in result_rows:
        response_id = str(row["response_id"])
        if _identity(row) != _identity(raw_by_id[response_id]):
            raise VerificationError(f"Week 7 result identity does not match raw response: {response_id}")
        if "panel_action" not in row or "majority_failure" not in row:
            raise VerificationError(f"Week 7 result has no outcome columns: {response_id}")
        parse_success = str(row["parse_success"]).strip()
        if parse_success not in {"0", "1"}:
            raise VerificationError(f"Week 7 result has invalid parse_success: {response_id}")
        if parse_success == "1":
            if not str(row["panel_action"]).strip() or not str(row["majority_failure"]).strip():
                raise VerificationError(f"Week 7 parsed result has blank outcome endpoints: {response_id}")
        else:
            unparsed_results += 1
    if unparsed_results > 48:
        raise VerificationError("Week 7 panel-unparsed responses exceed the registered 1% bound")

    ratings_by_id: dict[str, list[dict[str, Any]]] = {}
    for row in records["week07_judge_ratings"]:
        response_id = str(row["response_id"])
        ratings_by_id.setdefault(response_id, []).append(row)
    if set(ratings_by_id) != raw_ids:
        raise VerificationError("Week 7 rating coverage does not match raw response IDs")
    metadata_judges = _metadata_model_pairs(week7_metadata, "judges", 3)
    rating_judges = {
        (str(row["judge_model"]), str(row["judge_revision"]))
        for row in records["week07_judge_ratings"]
    }
    if rating_judges != metadata_judges:
        raise VerificationError("Week 7 rating judge set does not match metadata")
    for response_id, ratings in ratings_by_id.items():
        judge_pairs = {
            (str(row["judge_model"]), str(row["judge_revision"]))
            for row in ratings
        }
        if len(ratings) != 3 or judge_pairs != metadata_judges:
            raise VerificationError(f"Week 7 rating coverage requires the metadata judge panel: {response_id}")
        if any(_identity(row) != _identity(raw_by_id[response_id]) for row in ratings):
            raise VerificationError(f"Week 7 rating identity does not match raw response: {response_id}")


def _check_row_model_pairs(
    name: str,
    rows: list[dict[str, Any]],
    id_key: str,
    revision_key: str,
    lock: dict[str, str],
    found: dict[str, str],
) -> None:
    _require_row_fields(name, rows, (id_key, revision_key))
    for index, row in enumerate(rows, start=1):
        model_id, revision = _check_model_pair(
            row[id_key], row[revision_key], lock, f"{name} row {index}"
        )
        found[model_id] = revision


def _check_week6_judges(payload: dict[str, Any], lock: dict[str, str], found: dict[str, str]) -> None:
    judges = payload.get("judges")
    revisions = payload.get("judge_revisions")
    if not isinstance(judges, list) or not judges or not isinstance(revisions, dict):
        raise VerificationError("Week 6 judge metadata has no paired judge IDs and revisions")
    revision_values = list(revisions.values())
    if len(judges) != len(revision_values):
        raise VerificationError("Week 6 judge metadata has unequal judge ID and revision counts")
    for index, (judge_id, revision) in enumerate(zip(judges, revision_values), start=1):
        try:
            model_id, locked_revision = _check_model_pair(
                judge_id, revision, lock, f"Week 6 judge revision {index}"
            )
        except VerificationError as error:
            raise VerificationError(f"Week 6 judge revision {index} does not match its judge ID") from error
        found[model_id] = locked_revision


def _check_counted_provenance(
    records: dict[str, list[dict[str, Any]]],
    metadata: dict[str, dict[str, Any]],
    lock: dict[str, str],
    found: dict[str, str],
) -> None:
    _check_core_row_schemas(records)
    _check_cross_artifact_integrity(records, metadata["week-07/W07_Run_Metadata.json"])
    _check_row_model_pairs("week03_raw_generations", records["week03_raw_generations"], "model_id", "model_revision", lock, found)
    _check_row_model_pairs("week04_raw_generations", records["week04_raw_generations"], "model_id", "model_revision", lock, found)

    week5 = metadata["week-05/W05_Run_Metadata.json"]
    week5_model_id, week5_revision = _check_model_pair(
        week5.get("model_id"), week5.get("model_revision"), lock, "Week 5 run metadata"
    )
    model_key = week5.get("model_key")
    if not isinstance(model_key, str) or not model_key:
        raise VerificationError("Week 5 run metadata has no model_key")
    week5_rows = records["week05_raw_generations"]
    _check_row_model_pairs(
        "week05_raw_generations", week5_rows, "model_id", "model_revision", lock, found
    )
    if any(row["model_key"] != model_key for row in week5_rows):
        raise VerificationError("week05_raw_generations row model_key does not match Week 5 run metadata")
    if any(row["model_id"] != week5_model_id for row in week5_rows):
        raise VerificationError("week05_raw_generations row model_id does not match Week 5 run metadata")
    if any(row["model_revision"] != week5_revision for row in week5_rows):
        raise VerificationError("week05_raw_generations row model_revision does not match Week 5 run metadata")

    week6 = metadata["week-06/W06_Run_Metadata.json"]
    _, week6_revision = _check_model_pair(
        week6.get("model_id"), week6.get("model_revision"), lock, "Week 6 run metadata"
    )
    if any(row["model_revision"] != week6_revision for row in records["week06_raw_generations"]):
        raise VerificationError("week06_raw_generations row model_revision does not match Week 6 run metadata")

    _check_row_model_pairs("week07_raw_generations", records["week07_raw_generations"], "generator_model", "generator_revision", lock, found)
    _check_row_model_pairs("week07_judge_ratings", records["week07_judge_ratings"], "judge_model", "judge_revision", lock, found)
    _check_row_model_pairs("week07_results", records["week07_results"], "generator_model", "generator_revision", lock, found)


def _check_provenance(root: Path, counted_records: dict[str, list[dict[str, Any]]]) -> dict[str, str]:
    lock = _model_lock(root)
    found: dict[str, str] = {}
    metadata = {
        relative: _read_json(root / relative, "model metadata")
        for relative in (
            "week-04/W04_Run_Metadata.json",
            "week-05/W05_Run_Metadata.json",
            "week-06/W06_Run_Metadata.json",
            "week-06/W06_Analysis.json",
            "week-07/W07_Run_Metadata.json",
        )
    }
    for relative in (
        "week-04/W04_Run_Metadata.json",
        "week-05/W05_Run_Metadata.json",
        "week-06/W06_Run_Metadata.json",
        "week-07/W07_Run_Metadata.json",
    ):
        _check_model_metadata(metadata[relative], lock, relative, found)
    _check_week6_judges(metadata["week-06/W06_Analysis.json"], lock, found)
    _check_counted_provenance(counted_records, metadata, lock, found)
    if not found:
        raise VerificationError("fresh run contains no lock-validated model metadata")
    return dict(sorted(found.items()))


def _check_derived_deliverables(root: Path) -> None:
    json_requirements = {
        "week-08/W08_Pressure_Cue_Audit.json": ("schema_version", "status"),
        "week-10/W10_Judge_Sensitivity.json": ("schema_version", "inputs"),
    }
    for relative, fields in json_requirements.items():
        try:
            payload = _read_json(root / relative, "derived deliverable")
        except VerificationError as error:
            raise VerificationError(f"derived deliverable is invalid: {relative}") from error
        if not payload or any(not payload.get(field) for field in fields):
            raise VerificationError(f"derived deliverable is empty or incomplete: {relative}")
    for relative in ("week-08/W08_Pressure_Cue_Audit.md", "week-09/W09_Paper_Tables.md"):
        text = (root / relative).read_text(encoding="utf-8").strip()
        if len(text) < 32 or text.casefold() in {"todo", "placeholder", "tbd"}:
            raise VerificationError(f"derived deliverable is empty or placeholder text: {relative}")


def _check_figure_pairs(root: Path, stems: tuple[str, ...], directory: str) -> None:
    for stem in stems:
        png = root / directory / f"{stem}.png"
        svg = root / directory / f"{stem}.svg"
        if not png.is_file() or not svg.is_file():
            raise VerificationError(f"figure pair is incomplete: {directory}/{stem}")
        try:
            png_bytes = png.read_bytes()
        except OSError as error:
            raise VerificationError(f"figure PNG cannot be read: {png}") from error
        _check_png(png_bytes, png)
        try:
            root_element = ElementTree.parse(svg).getroot()
        except (OSError, ElementTree.ParseError) as error:
            raise VerificationError(f"figure SVG is invalid: {svg}") from error
        if root_element.tag.rsplit("}", 1)[-1] != "svg":
            raise VerificationError(f"figure SVG has no svg root: {svg}")


def _check_png(payload: bytes, path: Path) -> None:
    signature = b"\x89PNG\r\n\x1a\n"
    if not payload.startswith(signature):
        raise VerificationError(f"figure PNG is invalid: {path}")
    offset = len(signature)
    saw_header = saw_data = saw_end = False
    while offset < len(payload):
        if offset + 12 > len(payload):
            raise VerificationError(f"figure PNG is invalid: {path}")
        length = struct.unpack(">I", payload[offset : offset + 4])[0]
        chunk_type = payload[offset + 4 : offset + 8]
        chunk_end = offset + 12 + length
        if chunk_end > len(payload):
            raise VerificationError(f"figure PNG is invalid: {path}")
        data = payload[offset + 8 : offset + 8 + length]
        expected_crc = struct.unpack(">I", payload[offset + 8 + length : chunk_end])[0]
        if zlib.crc32(chunk_type + data) & 0xFFFFFFFF != expected_crc:
            raise VerificationError(f"figure PNG is invalid: {path}")
        if not saw_header:
            if chunk_type != b"IHDR" or length != 13:
                raise VerificationError(f"figure PNG is invalid: {path}")
            width, height = struct.unpack(">II", data[:8])
            if width == 0 or height == 0:
                raise VerificationError(f"figure PNG is invalid: {path}")
            saw_header = True
        elif chunk_type == b"IDAT":
            saw_data = True
        elif chunk_type == b"IEND":
            if length != 0 or chunk_end != len(payload):
                raise VerificationError(f"figure PNG is invalid: {path}")
            saw_end = True
            break
        offset = chunk_end
    if not (saw_header and saw_data and saw_end):
        raise VerificationError(f"figure PNG is invalid: {path}")


def _check_notebook(root: Path) -> None:
    notebook = _read_json(root / "week-07/W07_Analysis_Notebook.ipynb", "executed Week 7 notebook")
    cells = notebook.get("cells")
    if not isinstance(cells, list):
        raise VerificationError("executed Week 7 notebook has no cells")
    code_cells = [cell for cell in cells if isinstance(cell, dict) and cell.get("cell_type") == "code"]
    if len(code_cells) != NOTEBOOK_CODE_CELL_COUNT:
        raise VerificationError(f"executed Week 7 notebook expected {NOTEBOOK_CODE_CELL_COUNT} code cells, found {len(code_cells)}")
    for index, cell in enumerate(code_cells, start=1):
        if not isinstance(cell.get("execution_count"), int):
            raise VerificationError(f"executed Week 7 notebook code cell {index} has no execution count")
        outputs = cell.get("outputs")
        if not isinstance(outputs, list):
            raise VerificationError(f"executed Week 7 notebook code cell {index} has invalid outputs")
        if any(isinstance(output, dict) and output.get("output_type") == "error" for output in outputs):
            raise VerificationError(f"executed Week 7 notebook has an error output in code cell {index}")


def _check_prior_stages(receipt: dict[str, Any]) -> None:
    if receipt.get("mode") != "full":
        raise VerificationError("fresh verifier requires a full-run receipt")
    stages = receipt.get("stages")
    if not isinstance(stages, list):
        raise VerificationError("fresh verifier receipt has no stages")
    by_name = {entry.get("name"): entry for entry in stages if isinstance(entry, dict)}
    for name in FULL_STAGE_NAMES_BEFORE_VERIFY:
        entry = by_name.get(name)
        if not isinstance(entry, dict) or entry.get("status") != "passed" or entry.get("returncode") != 0:
            raise VerificationError(f"prior full-graph stage lacks passed evidence: {name}")


def _mark_incomplete(receipt_path: Path, verification_path: Path) -> None:
    try:
        verification_path.unlink(missing_ok=True)
    except OSError:
        pass
    try:
        receipt = _read_json(receipt_path, "run receipt")
        receipt["status"] = "incomplete"
        receipt["verification_pending"] = True
        _atomic_json_write(receipt_path, receipt)
    except BaseException:
        return


def verify(root: Path, receipt_path: Path) -> dict[str, object]:
    """Validate fresh evidence, then atomically record verification before completion."""
    run_root = Path(root).resolve()
    receipt_file = Path(receipt_path).resolve()
    verification_path = run_root / "fresh-verification.json"
    try:
        receipt = _read_json(receipt_file, "run receipt")
        _check_prior_stages(receipt)
        source_commit = receipt.get("source_commit")
        if not isinstance(source_commit, str) or COMMIT_RE.fullmatch(source_commit) is None:
            raise VerificationError("fresh verifier receipt has no immutable source commit")
        _require_paths(run_root)
        checked_counts, checked_row_counts, counted_records = _check_counts(run_root)
        model_revisions = _check_provenance(run_root, counted_records)
        _check_figure_pairs(run_root, FIGURE_STEMS, "week-07/figures")
        _check_figure_pairs(run_root, W09_FIGURE_STEMS, "week-09/figures")
        _check_notebook(run_root)
        _check_derived_deliverables(run_root)
        artifact_sha256 = {relative: _sha256(run_root / relative) for relative in REQUIRED_ARTIFACTS}
        evidence: dict[str, object] = {
            "schema_version": "ingen-fresh-verification-v1",
            "status": "complete",
            "source_commit": source_commit,
            "checked_counts": checked_counts,
            "checked_row_counts": checked_row_counts,
            "model_revisions": model_revisions,
            "artifact_sha256": artifact_sha256,
            "protocol_inputs_excluded_from_fresh_generation_counts": list(PROTOCOL_INPUTS),
        }
        _atomic_json_write(verification_path, evidence)
        receipt["status"] = "complete"
        receipt["verification_pending"] = False
        receipt["fresh_verification"] = verification_path.name
        try:
            _atomic_json_write(receipt_file, receipt)
        except BaseException:
            verification_path.unlink(missing_ok=True)
            raise
        return evidence
    except BaseException:
        _mark_incomplete(receipt_file, verification_path)
        raise


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--receipt", type=Path)
    args = parser.parse_args(argv)
    receipt = args.receipt or args.root / "run-receipt.json"
    try:
        evidence = verify(args.root, receipt)
    except VerificationError as error:
        print(f"FAIL: {error}")
        return 1
    print(json.dumps(evidence, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
